logging:
  level: INFO
  loggers:
    com.plaid: DEBUG

plaid_client_id: ${PLAID_CLIENT_ID}
plaid_secret: ${PLAID_SECRET}
plaid_products: ${PLAID_PRODUCTS:-"transactions"}
plaid_country_codes: ${PLAID_COUNTRY_CODES:-"US,CA"}
# Only required for Oauth:
# Set PLAID_REDIRECT_URI to 'http://localhost:8000/oauth-response.html'
# The OAuth redirect flow requires an endpoint on the developer's website
# that the bank website should redirect to. You will need to configure
# this redirect URI for your client ID through the Plaid developer dashboard
# at https://dashboard.plaid.com/team/api.
plaid_redirect_uri: ${PLAID_REDIRECT_URI:-""}
plaid_env: ${PLAID_ENV:-sandbox}

server:
  application_connectors:
    - type: http
      port: 8000
  admin_connectors:
    - type: http
      port: 8001
  rootPath: '/api'
